### PR TITLE
Added Hacking & bug bounty

### PR DESCRIPTION
**Pull request by fasalmbt**

### CODE REVIEW

**Comment by GopikrishnanSasikumar** [comment]
@fasalmbt good work! Please hyper link the links to texts. Add more emojis if possible.

**Review by AbhishekBaiju — COMMENTED** [review]
Hey Fasal, Good work!
Also, consider these things :
1. Use proper titles
2. Use Tabs and spaces to separate lists from heading
3. The **Next steps** section needs to be not _bulky_
4. Provide links for any resources you are mentioning 
5. Use fewer code-blocks 
6. Overall formatting should be similar to [here](https://github.com/tinkerhub-org/TinkerHub-Learning-Paths/blob/main/learning/python/README.md)!
7. And also Hyperlinks for all the links. those make a lot of difference!

**Comment by fasalmbt** [comment]
@AbhishekBaiju @GopikrishnanSasikumar  Done. Is it fine enough now , to merge?

**Comment by GopikrishnanSasikumar** [comment]
@fasalmbt this will do! Loved that final notes ❤️

**Pull request merged**
