### PR TITLE
Added Data Engineering Learning path

### PR DESCRIPTION
**Pull request by Anoop-Viswan**
First version for your review. Intentionally kept it short. Please take a look. All comments corrections and feedbacks appreciated

### CODE REVIEW

**Comment by GopikrishnanSasikumar** [comment]
@Anoop-Viswan cool stuff! I am feeling like each paragraph is a bit bulky. Would be great if we can separate it with lists and spaces.

**Comment by Anoop-Viswan** [comment]
Sounds good.  Formatting done as requested. Paragraphs organised as  dotted lists and spacings added for readability along with minor typo correction

**Review by AbhishekBaiju — COMMENTED** [review]
Hey Anoop, There is some typos and errors in there 
Also, the formatting should be or as close as other contents in the repo, for [ref](https://github.com/tinkerhub-org/TinkerHub-Learning-Paths/blob/main/learning/python/README.md).
I made some changes(grammatical) [here](https://drive.google.com/file/d/1qY_bpIqtQz8XDB_uml4xVWM41ohmnnij/view?usp=sharing)!
You can commit with the above-said changes

**Comment by gautamkrishnar** [comment]
@Anoop-Viswan please close this pull request and reopen it with the latest hugo format mentioned in the readme.

**Comment by gautamkrishnar** [comment]
Closing this one, please reopen after following the correct structure.

**Comment by gautamkrishnar** [comment]
Fixed myself 😄

**Pull request merged**
